project:
  type: website

website:
  title: "Pico Machine Learning"
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with a theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)."
    left: "&copy; CC-By Akshat Goel"
 
  navbar:
    navbar:
      right:
        - about.qmd

format:
  html:
    theme: [sandstone, custom.scss]
    mainfont: arial
    fontsize: 1rem
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left




# old _site.yml content below for comparison while converting to Quarto
#
# name: "."
# title: "NASA-Openscapes"
# description: |
#   NASA-Openscapes
# favicon: images/openscapes_hex.png  
# output_dir: "docs"
# navbar:
#   logo: images/openscapes_hex.png
#   href: https://openscapes.org
#   right:
#     - text: "Home"
#       href: index.html
#     - text: "About"
#       href: about.html
#     - text: "Mentors"
#       href: mentors.html
#     - text: "Champions"
#       href: champions.html 
#     - text: "Tutorials"
#       href: tutorials.html 
#     - text: "Events"
#       href: events.html
#     - icon: fab fa-twitter
#       href: https://twitter.com/openscapes
#     - icon: fab fa-github
#       href: https://github.com/nasa-openscapes
# output: distill::distill_article
# theme: theme.css

#project:
#  type: website

#website:
#  title: "Sunflowers | Strawberries | Machine Learning"
#  navbar:
#    right:
#      - about.qmd
#format:
#  html:
#    theme: simplex
#    css: styles.css



