---
title: Welcome To My Blog
author: Akshat Goel
date: '2024-01-01'
categories:
  - news
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.0
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

Welcome to my blog! Thanks for reading this. I'm Akshat. I am interested in economics, machine learning, and statistics, and I enjoy programming very much. It is an interesting time to be working in data science, because there is lots to learn and understand. My aim with this website is to expand my knowledge by researching and writing posts, and also to expose my side projects, in whatever state they are, for everyone to see.

I have been meaning to create this site for a while, but what finally made me do it was an exciting project idea: this year, I want to build a library for training and fine-tuning deep learning models, and use it to do my own experiments. 
There are existing frameworks, like Hugging Face, that already make this very easy. However, there are a few reasons that still make me want to go my own way:         

- In my experience with these libraries, it is difficult to get a low-level understanding of how a particular model works. Without this low-level understanding, I am hacking together random components on my projects just to get things going, which is not very intellectually satisfying.

- LinkedIn is full of unverified claims about what foundation models are capable of. It is very difficult to separate the signal from the noise. This is my way of actually simplifying and figuring out for myself what to believe and what not to believe.

- As machine learning systems become more capable, my perspective is that there need to be easy and transparent ways to understand the limitations and costs of deep learning models. I am uncomfortable with the increasingly likely reality that important decisions (whether you get a loan or not, what your insurance premium should be, whether you make it through airport security, whether you get access to rations from the government PDS shop) with real consequences will be taken by procedures which are largely black-boxes.

House rules for myself as a build the library:

- It has to be as simple as possible.
- Every model will have an annotated notebook that will explain each part of the code.
- The annotated notebook associated with each model will also explain try to explain the history, source, and limitations of each model.
- Each notebook will try to cut through the hype.
- Every model will have an associated Docker image for training and for deployment.

If you are still reading, welcome along for the ride! 
